/*
 * FakeStoreAPI
 * A free fake API for testing and prototyping e-commerce applications.
 *
 * The version of the OpenAPI document: v2.1.11
 * Contact: support@fakestoreapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Cart;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CartsApi
 */
@Disabled
public class CartsApiTest {

    private final CartsApi api = new CartsApi();

    /**
     * Add a new cart
     *
     * Create a new cart.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addCartTest() throws ApiException {
        Cart cart = null;
        Cart response = api.addCart(cart);
        // TODO: test validations
    }

    /**
     * Delete a cart
     *
     * Delete a specific cart by ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteCartTest() throws ApiException {
        Integer id = null;
        api.deleteCart(id);
        // TODO: test validations
    }

    /**
     * Get all carts
     *
     * Retrieve a list of all available carts.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllCartsTest() throws ApiException {
        List<Cart> response = api.getAllCarts();
        // TODO: test validations
    }

    /**
     * Get a single cart
     *
     * Retrieve details of a specific cart by ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCartByIdTest() throws ApiException {
        Integer id = null;
        Cart response = api.getCartById(id);
        // TODO: test validations
    }

    /**
     * Update a cart
     *
     * Update an existing cart by ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateCartTest() throws ApiException {
        Integer id = null;
        Cart cart = null;
        Cart response = api.updateCart(id, cart);
        // TODO: test validations
    }

}
