/*
 * FakeStoreAPI
 * A free fake API for testing and prototyping e-commerce applications.
 *
 * The version of the OpenAPI document: v2.1.11
 * Contact: support@fakestoreapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Product;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductsApi
 */
@Disabled
public class ProductsApiTest {

    private final ProductsApi api = new ProductsApi();

    /**
     * Add a new product
     *
     * Create a new product.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addProductTest() throws ApiException {
        Product product = null;
        Product response = api.addProduct(product);
        // TODO: test validations
    }

    /**
     * Delete a product
     *
     * Delete a specific product by ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteProductTest() throws ApiException {
        Integer id = null;
        api.deleteProduct(id);
        // TODO: test validations
    }

    /**
     * Get all products
     *
     * Retrieve a list of all available products.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllProductsTest() throws ApiException {
        List<Product> response = api.getAllProducts();
        // TODO: test validations
    }

    /**
     * Get a single product
     *
     * Retrieve details of a specific product by ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProductByIdTest() throws ApiException {
        Integer id = null;
        Product response = api.getProductById(id);
        // TODO: test validations
    }

    /**
     * Update a product
     *
     * Update an existing product by ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateProductTest() throws ApiException {
        Integer id = null;
        Product product = null;
        Product response = api.updateProduct(id, product);
        // TODO: test validations
    }

}
