/*
 * FakeStoreAPI
 * A free fake API for testing and prototyping e-commerce applications.
 *
 * The version of the OpenAPI document: v2.1.11
 * Contact: support@fakestoreapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.User;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
@Disabled
public class UsersApiTest {

    private final UsersApi api = new UsersApi();

    /**
     * Add a new user
     *
     * Create a new user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addUserTest() throws ApiException {
        User user = null;
        User response = api.addUser(user);
        // TODO: test validations
    }

    /**
     * Delete a user
     *
     * Delete a specific user by ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteUserTest() throws ApiException {
        Integer id = null;
        api.deleteUser(id);
        // TODO: test validations
    }

    /**
     * Get all users
     *
     * Retrieve a list of all users.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllUsersTest() throws ApiException {
        List<User> response = api.getAllUsers();
        // TODO: test validations
    }

    /**
     * Get a single user
     *
     * Retrieve details of a specific user by ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUserByIdTest() throws ApiException {
        Integer id = null;
        User response = api.getUserById(id);
        // TODO: test validations
    }

    /**
     * Update a user
     *
     * Update an existing user by ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateUserTest() throws ApiException {
        Integer id = null;
        User user = null;
        User response = api.updateUser(id, user);
        // TODO: test validations
    }

}
